
export enum InterfaceEvent {
	INPUT_KEY_DOWN = 50,
	INPUT_KEY_UP,

	INPUT_POINTER_PRESS,
	INPUT_POINTER_RELEASE,
	INPUT_POINTER_LOCK,
	INPUT_POINTER_MOVE,

	EDITOR_TOGGLE,
	EDITOR_SCENE_UPDATE,
	EDITOR_OBJECT_CREATE,
	EDITOR_OBJECT_UPDATE,
}